apiVersion: events.cloud.google.com/v1alpha1
kind: CloudPubSubSource
metadata:
  name: cloudpubsubsource-test
spec:
  topic: testing
  sink:
    ref:
    #   apiVersion: v1
    #   kind: Service
    #   name: vision
      apiVersion: eventing.knative.dev/v1alpha1
      kind: Broker
      name: default
